version: "3.7"

services:
  master1:
    build:
      context: .
      dockerfile: ./Redis.Master/Dockerfile
    image: master:latest
    ports:
      - "5001:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
        - MasterOptions__Children__0=http://child11:80
        - MasterOptions__Children__1=http://child12:80
        - MasterOptions__ReplicationActor=Master
        - MasterOptions__Slaves__0=http://master2:80
    container_name: redis-master1

  child11:
    build:
      context: .
      dockerfile: ./Redis.Child/Dockerfile
    image: child:latest
    ports:
      - "5002:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
    container_name: redis-child11

  child12:
    build:
      context: .
      dockerfile: ./Redis.Child/Dockerfile
    image: child:latest
    ports:
      - "5003:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
    container_name: redis-child12

  master2:
    build:
      context: .
      dockerfile: ./Redis.Master/Dockerfile
    image: master:latest
    ports:
      - "6001:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
        - MasterOptions__Children__0=http://child21:80
        - MasterOptions__Children__1=http://child22:80
        - MasterOptions__ReplicationActor=Slave
    container_name: redis-master2

  child21:
    build:
      context: .
      dockerfile: ./Redis.Child/Dockerfile
    image: child:latest
    ports:
      - "6002:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
    container_name: redis-child21

  child22:
    build:
      context: .
      dockerfile: ./Redis.Child/Dockerfile
    image: child:latest
    ports:
      - "6003:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
    container_name: redis-child22