version: "3.7"

services:
  master:
    build:
      context: .
      dockerfile: ./Redis.Master/Dockerfile
    image: master:latest
    ports:
      - "5001:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
        - MasterOptions__Children__0=http://child1:80
        - MasterOptions__Children__1=http://child2:80
    container_name: redis-master

  child1:
    build:
      context: .
      dockerfile: ./Redis.Child/Dockerfile
    image: child:latest
    ports:
      - "5002:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
    container_name: redis-child1

  child2:
    build:
      context: .
      dockerfile: ./Redis.Child/Dockerfile
    image: child:latest
    ports:
      - "5003:80"
    environment:
        - ASPNETCORE_URLS=http://*:80
        - ASPNETCORE_ENVIRONMENT=Release
    container_name: redis-child2